version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: WorkShop_09
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    environment:
      - FLASK_ENV=development
      - SQLALCHEMY_DATABASE_URI=postgresql://postgres:postgres@db:5432/WorkShop_09
    depends_on:
      - db
    ports:
      - "5000:5000"
    restart: always

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    environment:
      - VITE_API_BASE_URL=http://localhost:5000
    depends_on:
      - backend
    ports:
      - "5173:5173"
    restart: always

volumes:
  postgres_data:
